CREATE DATABASE IF NOT EXISTS demo_usuarios CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE demo_usuarios;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100),
  apellido_p VARCHAR(100),
  apellido_m VARCHAR(100),
  nacimiento DATE,
  genero ENUM('Masculino','Femenino','Indef.') DEFAULT 'Indef.',
  login VARCHAR(50) UNIQUE,
  pwd_hash VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fotos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT,
  base64 LONGTEXT,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

DELIMITER //
CREATE PROCEDURE ALTAS(IN iNOMBRE VARCHAR(100), IN iPAPELLIDO VARCHAR(100), IN iSAPELLIDO VARCHAR(100),
  IN iNAC DATE, IN iGENERO VARCHAR(20), IN iLOGIN VARCHAR(50), IN iPWD VARCHAR(255), IN iFOTO LONGTEXT)
BEGIN
  INSERT INTO usuarios(nombre, apellido_p, apellido_m, nacimiento, genero, login, pwd_hash)
  VALUES(iNOMBRE, iPAPELLIDO, iSAPELLIDO, iNAC, iGENERO, iLOGIN, iPWD);
  SET @uid = LAST_INSERT_ID();
  IF iFOTO IS NOT NULL THEN
    INSERT INTO fotos(usuario_id, base64) VALUES(@uid, iFOTO);
  END IF;
END //
CREATE PROCEDURE BAJAS(IN iID INT)
BEGIN
  DELETE FROM usuarios WHERE id=iID;
END //
CREATE PROCEDURE CAMBIOS(IN iID INT, IN iNOMBRE VARCHAR(100), IN iPAPELLIDO VARCHAR(100), IN iSAPELLIDO VARCHAR(100),
  IN iNAC DATE, IN iGENERO VARCHAR(20), IN iLOGIN VARCHAR(50), IN iPWD VARCHAR(255), IN iFOTO LONGTEXT)
BEGIN
  UPDATE usuarios
  SET nombre=iNOMBRE, apellido_p=iPAPELLIDO, apellido_m=iSAPELLIDO, nacimiento=iNAC, genero=iGENERO, login=iLOGIN,
      pwd_hash=COALESCE(iPWD,pwd_hash)
  WHERE id=iID;
  IF iFOTO IS NOT NULL THEN
    DELETE FROM fotos WHERE usuario_id=iID;
    INSERT INTO fotos(usuario_id, base64) VALUES(iID, iFOTO);
  END IF;
END //
DELIMITER ;
